let a = Number(prompt("Введите первое число"))
let b = Number(prompt("Введите второе число"))
alert(a + b)
alert(a - b)
alert(a / b)
alert(a * b)
alert(a ** b)
let c = Number(prompt("Введите число"))
alert(c + " * 1 =" + " " + c)
alert(c + " * 2 =" + " " + c*2)
alert(c + " * 3 =" + " " + c*3)
alert(c + " * 4 =" + " " + c*4)
alert(c + " * 5 =" + " " + c*5)
alert(c + " * 6 =" + " " + c*6)
alert(c + " * 7 =" + " " + c*7)
alert(c + " * 8 =" + " " + c*8)
alert(c + " * 9 =" + " " + c*9)
alert(c + " * 10 =" + " " + c*10)